core/BlogSite/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="BlogWebApp API",
        default_version="v1",
        description="This is the API documentation for the BlogWebApp.",
        terms_of_service="",
        contact=openapi.Contact(email="aghababaei1375@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url=reverse_lazy("post:list")), name="index"),
    path("account/", include("account.urls")),
    path("categories/", include("blog.urls.category")),
    path("posts/", include("blog.urls.post")),
    path("comments/", include("comment.urls")),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    path("captcha/", include("captcha.urls")),
    path("favicon.ico", RedirectView.as_view(url=settings.STATIC_URL + "img/favicon.ico", permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/account/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from .views import (
    SignUpView,
    VerificationResendView,
    VerificationConfirmView,
    CustomLoginView,
    CustomPasswordChangeView,
    CustomPasswordResetView,
    CustomPasswordResetConfirmView,
    UserInfoEditView,
    CaptchaView,
)

app_name = "account"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="index"), name="logout"),
    path("edit/", UserInfoEditView.as_view(), name="edit"),
    # Password
    path("password/change/", CustomPasswordChangeView.as_view(), name="password-change"),
    path("password/reset/", CustomPasswordResetView.as_view(), name="password-reset"),
    path(
        "password/reset/confirm/<str:token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    # Verification
    path("verify/resend/", VerificationResendView.as_view(), name="verify-resend"),
    path(
        "verify/confirm/<str:token>/",
        VerificationConfirmView.as_view(),
        name="verify-confirm",
    ),
    # API
    path("api/v1/", include("account.api.v1.urls")),
    # Captcha
    path("captcha/", CaptchaView.as_view(), name="get-captcha"),
]

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blogosphere | {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static "css/base_styles.css" %}">
    {% block extra_css %}{% endblock extra_css %}
    {% block script %}{% endblock script %}
</head>
<body>
    <div id="overlay" class="overlay hidden"></div>
    <nav class="nav">
        <div class="nav__logo">
            <a href="/">
                <img src="{% static "img/Blogosphere.png" %}" alt="Blogosphere" width="150">
            </a>
        </div>
    </nav>
    <div class="container">
        <div class="sidebar">
            <div class="sidebar_section hline">
                <img class="image" src="{% if not request.user.is_authenticated or not request.user.image %}{% static "img/profile.png" %}{% else %}{{ request.user.image.url }}{% endif %}" alt="profile">
                <h3>{% if request.user.is_authenticated %}{{ request.user.username }}{% else %}Guest{% endif %}</h3>
                <small>{% if request.user.is_authenticated %}{{ request.user.email }}{% endif %}</small>
            </div>

            {% if request.user.is_authenticated %}
            <div class="sidebar_section hline">
                <a href="{% url "post:list" %}" class="button">Explore</a>
                <a href="{% url "post:create" %}" class="button">New Post</a>
            </div>
            {% if request.user.is_superuser %}
            <div class="sidebar_section hline">
                <a href="{% url "category:list" %}" class="button">Category Management</a>
            </div>
            {% endif %}
            <div class="sidebar_section hline">
                <a href="{% url "account:edit" %}" class="button">Edit Profile Info</a>
                <a href="{% url "account:password-change" %}" class="button">Change Password</a>
                {% if not request.user.is_verified %}
                <a href="{% url "account:verify-resend" %}" class="button">Verify Email</a>
                {% endif %}
                <form class="sidebar_section" action="{% url "account:logout" %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Log Out" class="button">
                </form>
            </div>
            {% else %}
            <div class="sidebar_section hline">
                <a href="{% url "account:login" %}" class="button">Log In</a>
                <a href="{% url "account:signup" %}" class="button">Sign Up</a>
                <a href="{% url "account:password-reset" %}" class="button">Reset Password</a>
            </div>
            {% endif %}

            <div class="sidebar_section">
                <a href="{% url "schema-swagger-ui" %}" class="button">API Doc - Swagger</a>
                <a href="{% url "schema-redoc" %}" class="button">API Doc - Redoc</a>
            </div>
        </div>

        <main class="main">
            {% block content %}
            {% endblock content %}
        </main>

        {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="message {{ message.tags }}">
                    {% with img_name="img/"|add:message.tags|add:".svg" %}
                    <img src="{% static img_name %}" alt="{{ message.tags }}" width="32" height="32">
                    {% endwith %}
                    <p>{{ message }}</p>
                    <button class="close" onclick="this.parentElement.style.display='none';">&times;</button>
                    <div class="progress_container"><div class="progressbar"></div></div>
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>

    <script src="{% static "js/base_scripts.js" %}"></script>

    {% block extra_js %}{% endblock extra_js %}
</body>
</html>